### ISSUE TITLE
Add identifier to manifest.json

### ISSUE THREAD

**Issue by mludowise** [pixelpillow/copy-paste-guides#2]
This plugin cannot automatically update in [Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/) because it is missing an identifier in the manifest.json file. See http://developer.sketchapp.com/introduction/plugin-bundles/ for more info.

**Comment by joelcox** [comment]
Fixed in e2d8e67820073b3e502c1a5adb98dd5850a8e24e. Thanks for reporting.
